### ISSUE TITLE
Nov 10 2020 - Regulation Innovation SIG Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/open-regtech#2]
# Regulation Innovation SIG
## Date
Nov 10 2020 - 12pm EST / 5pm GMT

## Untracked attendees
- Adam Hurwitz / Microsoft
- Alan Watson / Morgan Stanley
- Ashley Nelle-Davis / Data Coalition
- David Cowland / Fidelity
- Ian Purvis / Openfin
- Mukund Umalkar / ING
- Philip Spivey / Bleckwen
- Tosha Ellison / FINOS
- Vishal Kapur / Deloitte

## Agenda
- [x] Convene & roll call (5mins) - Name, Organization and Interest in the SIG
- [x] FINOS intro (5-10 minutes)
- [x] Regulation Innovation SIG intro (10-15 minutes)
- [x] Focus areas discussion: Topics that could be of interest, existing code/ work that could be leveraged?
    - Interoperability - AML
    - Digital Regulatory Reporting
    - Taxonomies - Horizon Scanning
    - Payments
    - Data privacy
    - Data standards 
- [x] Next steps
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] FINOS to coordinate demos/ presentations on potential areas of interest for next session
- [x] FINOS to share presentation deck - _see [20201110 Regulation Innovation SIG 20Kick-Off.pdf](https://github.com/finos/open-regtech/blob/master/resources/20201110%20Regulation%20Innovation%20SIG%20Kick-Off.pdf)_

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=mc39f602c94618d58437eac6707b6b5ab
- Meeting number: 127 988 1411
- Password: d9kKJPdX5C9
- More ways to join: 
    - Join by video system: Dial 1279881411@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 988 1411

**Comment by adamj-codethink** [comment]
Hey o/

**Comment by brooklynrob** [comment]
I'm here!

**Comment by adhurwit** [comment]
Here

**Comment by pmhunter** [comment]
Here

**Comment by srholt62** [comment]
Hi

**Comment by mvanbuskirk** [comment]
I am here

**Comment by nigelcobb** [comment]
here

**Comment by pbouda** [comment]
Here

**Comment by aitana16** [comment]
hi!

**Comment by stephengoldbaum** [comment]
I was there

**Comment by toshaellison** [comment]
I was there.
